// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SubastaYa.Infrastructure.Context;

#nullable disable

namespace SubastaYa.Infrastructure.Migrations
{
    [DbContext(typeof(SubastaYaDbContext))]
    [Migration("20260915043413_ActualizarPasswordHashBCrypt")]
    partial class ActualizarPasswordHashBCrypt
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SubastaYa.Domain.Entities.AuditoriaLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DetalleJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Entidad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EntidadId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("AuditoriaLogs");
                });

            modelBuilder.Entity("SubastaYa.Domain.Entities.Billetera", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("SaldoDisponible")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SaldoRetenido")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SaldoTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId")
                        .IsUnique();

                    b.ToTable("Billeteras");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            SaldoDisponible = 0m,
                            SaldoRetenido = 0m,
                            SaldoTotal = 0m,
                            UsuarioId = 1,
                            Version = 1
                        },
                        new
                        {
                            Id = 2,
                            SaldoDisponible = 105000m,
                            SaldoRetenido = 45000m,
                            SaldoTotal = 150000m,
                            UsuarioId = 2,
                            Version = 1
                        },
                        new
                        {
                            Id = 3,
                            SaldoDisponible = 200000m,
                            SaldoRetenido = 0m,
                            SaldoTotal = 200000m,
                            UsuarioId = 3,
                            Version = 1
                        },
                        new
                        {
                            Id = 4,
                            SaldoDisponible = 500m,
                            SaldoRetenido = 0m,
                            SaldoTotal = 500m,
                            UsuarioId = 4,
                            Version = 1
                        });
                });

            modelBuilder.Entity("SubastaYa.Domain.Entities.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UrlIcono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categorias");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Tecnología",
                            UrlIcono = "icon-tech"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Coleccionables",
                            UrlIcono = "icon-col"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Indumentaria",
                            UrlIcono = "icon-ropa"
                        },
                        new
                        {
                            Id = 4,
                            Nombre = "Vehículos",
                            UrlIcono = "icon-auto"
                        });
                });

            modelBuilder.Entity("SubastaYa.Domain.Entities.Puja", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CompradorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaPuja")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Monto")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SubastaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CompradorId");

                    b.HasIndex("SubastaId");

                    b.ToTable("Pujas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CompradorId = 3,
                            FechaPuja = new DateTime(2026, 9, 15, 4, 19, 10, 219, DateTimeKind.Utc).AddTicks(6208),
                            Monto = 40000m,
                            SubastaId = 1
                        },
                        new
                        {
                            Id = 2,
                            CompradorId = 2,
                            FechaPuja = new DateTime(2026, 9, 15, 4, 29, 10, 219, DateTimeKind.Utc).AddTicks(6208),
                            Monto = 45000m,
                            SubastaId = 1
                        },
                        new
                        {
                            Id = 3,
                            CompradorId = 2,
                            FechaPuja = new DateTime(2026, 9, 14, 4, 34, 10, 219, DateTimeKind.Utc).AddTicks(6208),
                            Monto = 35000m,
                            SubastaId = 4
                        });
                });

            modelBuilder.Entity("SubastaYa.Domain.Entities.Subasta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("IncrementoMinimo")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PrecioBase")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UrlImagen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VendedorId")
                        .HasColumnType("int");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("VendedorId");

                    b.ToTable("Subastas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoriaId = 1,
                            Descripcion = "Disfrutá de una carga instantánea gracias a su SSD de alta velocidad de 825GB. Olvidate de las esperas y sumergite directamente en la acción con gráficos impresionantes en 4K y tecnología Ray Tracing, que añade un realismo asombroso con sombras y reflejos fieles a la realidad.",
                            Estado = 2,
                            FechaFin = new DateTime(2026, 9, 15, 5, 4, 10, 219, DateTimeKind.Utc).AddTicks(6208),
                            FechaInicio = new DateTime(2026, 9, 15, 3, 34, 10, 219, DateTimeKind.Utc).AddTicks(6208),
                            IncrementoMinimo = 1000m,
                            PrecioBase = 10000m,
                            Titulo = "PlayStation 5",
                            UrlImagen = "https://i.ibb.co/jPwDCZ16/descarga-2026-03-31-T111030-325.png",
                            VendedorId = 1,
                            Version = 1
                        },
                        new
                        {
                            Id = 2,
                            CategoriaId = 1,
                            Descripcion = "Elevá tu experiencia tecnológica con el Apple iPhone 13 (128 GB) en un sofisticado color Azul. Este smartphone combina un rendimiento excepcional con un diseño elegante y funciones avanzadas para que disfrutes de cada momento al máximo. Chip A15 Bionic Súper Rápido. Sistema de Cámaras Doble Avanzado. Pantalla Super Retina XDR Brillante de 6.1 pulgadas.",
                            Estado = 2,
                            FechaFin = new DateTime(2026, 9, 15, 4, 35, 10, 219, DateTimeKind.Utc).AddTicks(6208),
                            FechaInicio = new DateTime(2026, 9, 15, 2, 34, 10, 219, DateTimeKind.Utc).AddTicks(6208),
                            IncrementoMinimo = 500m,
                            PrecioBase = 5000m,
                            Titulo = "Apple iPhone 13",
                            UrlImagen = "https://i.ibb.co/NvpNhBw/2b9cec46-e3fb-4fd3-b83e-6093aa11f3ef.webp",
                            VendedorId = 1,
                            Version = 1
                        },
                        new
                        {
                            Id = 3,
                            CategoriaId = 2,
                            Descripcion = "Figuras de acción articuladas con sus accesorios de lucha listos para el combate. Dimensiones: 30 cm. Personajes: HUNTSMAN, WHITE SHADE, SKULL CRACKER.",
                            Estado = 1,
                            FechaFin = new DateTime(2026, 9, 17, 4, 34, 10, 219, DateTimeKind.Utc).AddTicks(6208),
                            FechaInicio = new DateTime(2026, 9, 16, 4, 34, 10, 219, DateTimeKind.Utc).AddTicks(6208),
                            IncrementoMinimo = 2000m,
                            PrecioBase = 20000m,
                            Titulo = "Figura De Accion Articulada",
                            UrlImagen = "https://i.ibb.co/SXyKgwsB/200240-800-auto.webp",
                            VendedorId = 1,
                            Version = 1
                        },
                        new
                        {
                            Id = 4,
                            CategoriaId = 3,
                            Descripcion = "Confeccionada con materiales reciclados y tecnología AEROREADY para mantener la comodidad y frescura en todo momento. Ajustado. Cuello en V. 100% poliéster reciclado. AEROREADY. 8 Tiras aplicadas. Escudo de Boca Juniors tejido. Detalle “1905” aplicado en la nuca. Franja icónica dorada.",
                            Estado = 2,
                            FechaFin = new DateTime(2026, 9, 15, 4, 24, 10, 219, DateTimeKind.Utc).AddTicks(6208),
                            FechaInicio = new DateTime(2026, 9, 13, 4, 34, 10, 219, DateTimeKind.Utc).AddTicks(6208),
                            IncrementoMinimo = 1500m,
                            PrecioBase = 30000m,
                            Titulo = "Camiseta de Fútbol",
                            UrlImagen = "https://i.ibb.co/chydTrMW/JJ4286-01.webp",
                            VendedorId = 1,
                            Version = 1
                        },
                        new
                        {
                            Id = 5,
                            CategoriaId = 4,
                            Descripcion = "La Kanji ON WHEELS Rodado 29 es una bicicleta de montaña diseñada para quienes buscan rendimiento, comodidad y durabilidad en cada recorrido. Con un diseño moderno y componentes confiables, es ideal tanto para caminos urbanos exigentes como para aventuras off-road.",
                            Estado = 2,
                            FechaFin = new DateTime(2026, 9, 15, 4, 4, 10, 219, DateTimeKind.Utc).AddTicks(6208),
                            FechaInicio = new DateTime(2026, 9, 13, 4, 34, 10, 219, DateTimeKind.Utc).AddTicks(6208),
                            IncrementoMinimo = 5000m,
                            PrecioBase = 50000m,
                            Titulo = "Bicicleta Kanji R/29",
                            UrlImagen = "https://i.ibb.co/d4yNsNSs/840-kaj-289.webp",
                            VendedorId = 1,
                            Version = 1
                        });
                });

            modelBuilder.Entity("SubastaYa.Domain.Entities.TransaccionLedger", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BilleteraId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Monto")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("SubastaId")
                        .HasColumnType("int");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BilleteraId");

                    b.HasIndex("SubastaId");

                    b.ToTable("TransaccionesLedger");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BilleteraId = 2,
                            Fecha = new DateTime(2026, 9, 14, 4, 34, 10, 219, DateTimeKind.Utc).AddTicks(6208),
                            Monto = 150000m,
                            Tipo = 1
                        },
                        new
                        {
                            Id = 2,
                            BilleteraId = 2,
                            Fecha = new DateTime(2026, 9, 15, 4, 29, 10, 219, DateTimeKind.Utc).AddTicks(6208),
                            Monto = 45000m,
                            SubastaId = 1,
                            Tipo = 2
                        },
                        new
                        {
                            Id = 3,
                            BilleteraId = 3,
                            Fecha = new DateTime(2026, 9, 14, 4, 34, 10, 219, DateTimeKind.Utc).AddTicks(6208),
                            Monto = 200000m,
                            Tipo = 1
                        },
                        new
                        {
                            Id = 4,
                            BilleteraId = 4,
                            Fecha = new DateTime(2026, 9, 14, 4, 34, 10, 219, DateTimeKind.Utc).AddTicks(6208),
                            Monto = 500m,
                            Tipo = 1
                        });
                });

            modelBuilder.Entity("SubastaYa.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "vendedor@test.com",
                            FechaRegistro = new DateTime(2026, 9, 15, 4, 34, 10, 219, DateTimeKind.Utc).AddTicks(6208),
                            Nombre = "Vendedor",
                            PasswordHash = "$2a$11$e/y8Yw0P5g9A1K4v1f8Sye1O6u6Iq3q5/6W9U0.4A8S.3A2A8S.2S"
                        },
                        new
                        {
                            Id = 2,
                            Email = "comprador1@test.com",
                            FechaRegistro = new DateTime(2026, 9, 15, 4, 34, 10, 219, DateTimeKind.Utc).AddTicks(6208),
                            Nombre = "Comprador 1",
                            PasswordHash = "$2a$11$e/y8Yw0P5g9A1K4v1f8Sye1O6u6Iq3q5/6W9U0.4A8S.3A2A8S.2S"
                        },
                        new
                        {
                            Id = 3,
                            Email = "comprador2@test.com",
                            FechaRegistro = new DateTime(2026, 9, 15, 4, 34, 10, 219, DateTimeKind.Utc).AddTicks(6208),
                            Nombre = "Comprador 2",
                            PasswordHash = "$2a$11$e/y8Yw0P5g9A1K4v1f8Sye1O6u6Iq3q5/6W9U0.4A8S.3A2A8S.2S"
                        },
                        new
                        {
                            Id = 4,
                            Email = "sinfondos@test.com",
                            FechaRegistro = new DateTime(2026, 9, 15, 4, 34, 10, 219, DateTimeKind.Utc).AddTicks(6208),
                            Nombre = "Sin Fondos",
                            PasswordHash = "$2a$11$e/y8Yw0P5g9A1K4v1f8Sye1O6u6Iq3q5/6W9U0.4A8S.3A2A8S.2S"
                        });
                });

            modelBuilder.Entity("SubastaYa.Domain.Entities.AuditoriaLog", b =>
                {
                    b.HasOne("SubastaYa.Domain.Entities.Usuario", "Usuario")
                        .WithMany("AuditoriaLogs")
                        .HasForeignKey("UsuarioId");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SubastaYa.Domain.Entities.Billetera", b =>
                {
                    b.HasOne("SubastaYa.Domain.Entities.Usuario", "Usuario")
                        .WithOne("Billetera")
                        .HasForeignKey("SubastaYa.Domain.Entities.Billetera", "UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SubastaYa.Domain.Entities.Puja", b =>
                {
                    b.HasOne("SubastaYa.Domain.Entities.Usuario", "Comprador")
                        .WithMany("PujasRealizadas")
                        .HasForeignKey("CompradorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SubastaYa.Domain.Entities.Subasta", "Subasta")
                        .WithMany("Pujas")
                        .HasForeignKey("SubastaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Comprador");

                    b.Navigation("Subasta");
                });

            modelBuilder.Entity("SubastaYa.Domain.Entities.Subasta", b =>
                {
                    b.HasOne("SubastaYa.Domain.Entities.Categoria", "Categoria")
                        .WithMany("Subastas")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SubastaYa.Domain.Entities.Usuario", "Vendedor")
                        .WithMany("SubastasPublicadas")
                        .HasForeignKey("VendedorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Vendedor");
                });

            modelBuilder.Entity("SubastaYa.Domain.Entities.TransaccionLedger", b =>
                {
                    b.HasOne("SubastaYa.Domain.Entities.Billetera", "Billetera")
                        .WithMany("Movimientos")
                        .HasForeignKey("BilleteraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SubastaYa.Domain.Entities.Subasta", "Subasta")
                        .WithMany("TransaccionesLedger")
                        .HasForeignKey("SubastaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Billetera");

                    b.Navigation("Subasta");
                });

            modelBuilder.Entity("SubastaYa.Domain.Entities.Billetera", b =>
                {
                    b.Navigation("Movimientos");
                });

            modelBuilder.Entity("SubastaYa.Domain.Entities.Categoria", b =>
                {
                    b.Navigation("Subastas");
                });

            modelBuilder.Entity("SubastaYa.Domain.Entities.Subasta", b =>
                {
                    b.Navigation("Pujas");

                    b.Navigation("TransaccionesLedger");
                });

            modelBuilder.Entity("SubastaYa.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("AuditoriaLogs");

                    b.Navigation("Billetera");

                    b.Navigation("PujasRealizadas");

                    b.Navigation("SubastasPublicadas");
                });
#pragma warning restore 612, 618
        }
    }
}
