// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SubastaYa.Infrastructure.Context;

#nullable disable

namespace SubastaYa.Infrastructure.Migrations
{
    [DbContext(typeof(SubastaYaDbContext))]
    [Migration("20261007042655_UpdateDomainConstraintsAndRemoveSeedData")]
    partial class UpdateDomainConstraintsAndRemoveSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SubastaYa.Domain.Entities.AuditoriaLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DetalleJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Entidad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EntidadId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("AuditoriaLogs");
                });

            modelBuilder.Entity("SubastaYa.Domain.Entities.Billetera", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("SaldoDisponible")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SaldoRetenido")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SaldoTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId")
                        .IsUnique();

                    b.ToTable("Billeteras", t =>
                        {
                            t.HasCheckConstraint("CK_Billetera_SaldoDisponible_Positivo", "[SaldoDisponible] >= 0");

                            t.HasCheckConstraint("CK_Billetera_SaldoRetenido_Positivo", "[SaldoRetenido] >= 0");

                            t.HasCheckConstraint("CK_Billetera_SaldoTotal_Positivo", "[SaldoTotal] >= 0");
                        });
                });

            modelBuilder.Entity("SubastaYa.Domain.Entities.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UrlIcono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("SubastaYa.Domain.Entities.Puja", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CompradorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaPuja")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Monto")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SubastaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CompradorId");

                    b.HasIndex("SubastaId");

                    b.ToTable("Pujas", t =>
                        {
                            t.HasCheckConstraint("CK_Puja_Monto_MayorACero", "[Monto] > 0");
                        });
                });

            modelBuilder.Entity("SubastaYa.Domain.Entities.Subasta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("IncrementoMinimo")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PrecioBase")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UrlImagen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VendedorId")
                        .HasColumnType("int");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("VendedorId");

                    b.ToTable("Subastas", t =>
                        {
                            t.HasCheckConstraint("CK_Subasta_IncrementoMinimo_MayorACero", "[IncrementoMinimo] > 0");

                            t.HasCheckConstraint("CK_Subasta_PrecioBase_Positivo", "[PrecioBase] >= 0");
                        });
                });

            modelBuilder.Entity("SubastaYa.Domain.Entities.TransaccionLedger", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BilleteraId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Monto")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("SubastaId")
                        .HasColumnType("int");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BilleteraId");

                    b.HasIndex("SubastaId");

                    b.ToTable("TransaccionesLedger", t =>
                        {
                            t.HasCheckConstraint("CK_TransaccionLedger_Monto_MayorACero", "[Monto] > 0");
                        });
                });

            modelBuilder.Entity("SubastaYa.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("SubastaYa.Domain.Entities.AuditoriaLog", b =>
                {
                    b.HasOne("SubastaYa.Domain.Entities.Usuario", "Usuario")
                        .WithMany("AuditoriaLogs")
                        .HasForeignKey("UsuarioId");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SubastaYa.Domain.Entities.Billetera", b =>
                {
                    b.HasOne("SubastaYa.Domain.Entities.Usuario", "Usuario")
                        .WithOne("Billetera")
                        .HasForeignKey("SubastaYa.Domain.Entities.Billetera", "UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SubastaYa.Domain.Entities.Puja", b =>
                {
                    b.HasOne("SubastaYa.Domain.Entities.Usuario", "Comprador")
                        .WithMany("PujasRealizadas")
                        .HasForeignKey("CompradorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SubastaYa.Domain.Entities.Subasta", "Subasta")
                        .WithMany("Pujas")
                        .HasForeignKey("SubastaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Comprador");

                    b.Navigation("Subasta");
                });

            modelBuilder.Entity("SubastaYa.Domain.Entities.Subasta", b =>
                {
                    b.HasOne("SubastaYa.Domain.Entities.Categoria", "Categoria")
                        .WithMany("Subastas")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SubastaYa.Domain.Entities.Usuario", "Vendedor")
                        .WithMany("SubastasPublicadas")
                        .HasForeignKey("VendedorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Vendedor");
                });

            modelBuilder.Entity("SubastaYa.Domain.Entities.TransaccionLedger", b =>
                {
                    b.HasOne("SubastaYa.Domain.Entities.Billetera", "Billetera")
                        .WithMany("Movimientos")
                        .HasForeignKey("BilleteraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SubastaYa.Domain.Entities.Subasta", "Subasta")
                        .WithMany("TransaccionesLedger")
                        .HasForeignKey("SubastaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Billetera");

                    b.Navigation("Subasta");
                });

            modelBuilder.Entity("SubastaYa.Domain.Entities.Billetera", b =>
                {
                    b.Navigation("Movimientos");
                });

            modelBuilder.Entity("SubastaYa.Domain.Entities.Categoria", b =>
                {
                    b.Navigation("Subastas");
                });

            modelBuilder.Entity("SubastaYa.Domain.Entities.Subasta", b =>
                {
                    b.Navigation("Pujas");

                    b.Navigation("TransaccionesLedger");
                });

            modelBuilder.Entity("SubastaYa.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("AuditoriaLogs");

                    b.Navigation("Billetera");

                    b.Navigation("PujasRealizadas");

                    b.Navigation("SubastasPublicadas");
                });
#pragma warning restore 612, 618
        }
    }
}
